name: "ContentstackUtils CI"

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  iOS:
    name: Test iOS
    runs-on: macos-latest
    env:
      DEVELOPER_DIR: /Applications/Xcode_11.4.app/Contents/Developer
    strategy:
      matrix:
        destination: ["OS=13.4,name=iPhone 11 Pro"]
    steps:
      - name: iOS - ${{ matrix.destination }}
        run: xcodebuild -project "ContentstackUtils.xcodeproje" -scheme "ContentstackUtils-Package" -destination "${{ matrix.destination }}" test | xcpretty

